variables:
  DEPLOY_FOLDER: "resourcecalculator.com"

stages:
  - build
  # - test
  - deploy


build-site:
  image: ubuntu:18.04
  stage: build
  script:
    - apt-get update
    - apt-get install python3 -y
    - python3 --version
    - apt-get install python3-pip -y
    - pip3 install -r requirements.txt

    # Build System Website
    - python3 build.py


deploy-dreamhost-prod:
  image: asherglick/webdeploy:20170802
  stage: deploy
  script:
    # Run ssh-agent (inside the build environment)
    - eval $(ssh-agent -s)
    # Add the SSH key stored in the environment to the agent store
    - ssh-add <(echo "$PROD_SSH_PRIVATE_KEY")
    # For Docker builds disable host key checking. Be aware that by adding that
    # you are susceptible to man-in-the-middle attacks.
    # WARNING: Use this only with the Docker executor, if you use it with shell
    # you will overwrite your user's SSH config.
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - ssh $PROD_USER@$PROD_HOST ls



    # Sync over the files
    # - rsync --recursive --archive --verbose -e ssh --exclude-from ".sync_exclusions" --include 'output/*' --delete . $PROD_USER@$PROD_HOST:/home/$PROD_USER/$DEPLOY_FOLDER/
    - ls output/*

  only:
    - master